[project]
name = 'stack-token'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.stack-token]
path = 'contracts/stack-token.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
